# Generated by Django 5.0.2 on 2024-02-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=20)),
                ("balance", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
        migrations.AlterField(
            model_name="user",
            name="card_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="polls.card"
            ),
        ),
    ]
