# Generated by Django 5.0.2 on 2024-02-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_card_remove_user_balance_alter_user_card_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="card_id",
            new_name="card",
        ),
        migrations.RemoveField(
            model_name="card",
            name="card_id",
        ),
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
