# Generated by Django 5.0.2 on 2024-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_card_id_user_card_remove_card_card_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
