# Generated by Django 5.0.2 on 2024-02-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_user_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="polls.card",
            ),
        ),
    ]
