# Generated by Django 5.0.2 on 2024-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_alter_user_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
